MT-Bench:
  language: en

  max_score: 10

  background: null

  case: null

  question:
    loading_way: json
    path:
      - data/mt-bench/question.jsonl
    key: turns
    prompt_template: "Question: {question}"

  reference_answer:
    loading_way: json
    path:
      - data/mt-bench/question.jsonl
    key: reference
    prompt_template: "Reference Answer: {reference_answer}"

  judge_prompt:
    loading_way: txt
    path: data/mt-bench/scoring_criteria_without_reference.txt

  judge_prompt_with_reference:
    loading_way: txt
    path: data/mt-bench/scoring_criteria_with_reference.txt


MedEthicsMatrixCase:
  language: zh

  max_score: 5

  background: null

  case:
    loading_way: csv
    path:
      - data/MedEthicsMatrixCase/MedEthicsMatrixCase.csv
    key: case
    prompt_template: "Case: {case}"

  question:
    loading_way: csv
    path:
      - data/MedEthicsMatrixCase/MedEthicsMatrixCase.csv
    key: questions
    prompt_template: "Question: {question}"

  reference_answer: null

  scoring_criteria: llmjudge

  judge_prompt:
    loading_way: txt
    path: data/MedEthicsMatrixCase/scoring_criteria.txt

  judge_prompt_with_reference: null


DxBench:
  language: zh

  max_score: 100

  background: null
  case:
    loading_way: json
    path:
      - data/DXBench/DxBench_zh.json
    key: 
      - explicit_symptoms
      - implicit_symptoms

    prompt_template: |
      患者显性症状（患者明确表达或明显可见的症状）：
      {explicit_symptoms}
      
      患者隐性症状（通过检查、病史或观察发现的症状）：
      {implicit_symptoms}
      
      候选疾病：{candidate_diseases}
      
      说明：症状后的"True"表示该症状存在，"False"表示该症状不存在。

  question: 
    loading_way: json
    path:
      - data/DXBench/DxBench_zh.json
    key: candidate_diseases

    prompt_template: |
      候选疾病: {candidate_diseases}

      请根据患者的症状信息，从候选疾病中选择最可能的诊断结果。请只回答疾病名称。  
      

  reference_answer:
    loading_way: json
    path:
      - data/DXBench/DxBench_zh.json
    key: disease

  scoring_criteria: accuracy

  judge_prompt: null

  judge_prompt_with_reference: null

